// apps/tauri-controls-svelte/src/lib/WindowControls.svelte
<script lang="ts">
  import { osType } from "$lib/utils/os"
  import { cn } from "$lib/utils/utils"
  import Gnome from "./controls/linux/Gnome.svelte"
  import MacOs from "./controls/MacOs.svelte"
  import Windows from "./controls/Windows.svelte"

  export let platform = "windows"
  export let hide = false
  export let hideMethod = "display"
  export let justify = false

  const customClass = cn(
    "tauri-controls flex",
    $$props.class,
    hide && (hideMethod === "display" ? "hidden" : "invisible")
  )

  // Determine the default platform based on the operating system if platform not specified
  if (!platform) {
    switch (osType) {
      case "macos":
        platform = "macos"
        break
      case "linux":
        platform = "gnome"
        break
      default:
        platform = "windows"
    }
  }
</script>

{#if platform === "windows"}
  <Windows {...$$props} class={cn(customClass, justify && "ml-auto")} />
{:else if platform === "macos"}
  <MacOs {...$$props} class={cn(customClass, justify && "ml-0")} />
{:else if platform === "gnome"}
  <Gnome {...$$props} class={cn(customClass, justify && "ml-auto")} />
{:else}
  <Windows {...$$props} class={cn(customClass, justify && "ml-auto")} />
{/if}

// apps/tauri-controls-vue/src/tauri-controls/WindowControls.vue
<script setup lang="ts">
import { twMerge } from "tailwind-merge"
import { onMounted } from "vue"
import Gnome from "./controls/linux/Gnome.vue"
import MacOs from "./controls/MacOs.vue"
import Windows from "./controls/Windows.vue"
import type { WindowControlsProps } from "./types"
import { getOsType } from "./utils/os"

defineOptions({
  inheritAttrs: false,
})

const props = withDefaults(defineProps<WindowControlsProps>(), {
  justify: false,
  hide: false,
  hideMethod: "display",
  className: "",
})

let platform = props.platform
onMounted(() => {
  getOsType().then((type) => {
    if (!platform) {
      switch (type) {
        case "macos":
          platform = "macos"
          break
        case "linux":
          platform = "gnome"
          break
        default:
          platform = "windows"
      }
    }
  })
})

const customClass = twMerge(
  "tauri-controls flex",
  props.className,
  props.hide && (props.hideMethod === "display" ? "hidden" : "invisible")
)
</script>

<template>
  <Windows
    v-if="platform === 'windows'"
    :class="twMerge(customClass, props.justify && 'ml-auto')"
  />
  <MacOs
    v-else-if="platform === 'macos'"
    :class="twMerge(customClass, props.justify && 'ml-0')"
  />
  <Gnome
    v-else-if="platform === 'gnome'"
    :class="twMerge(customClass, props.justify && 'ml-auto')"
  />
  <Windows v-else :class="twMerge(customClass, props.justify && 'ml-auto')" />
</template>
