// apps/tauri-controls-vue/src/App.vue
<script setup lang="ts">
import LogoSvg from "./components/LogoSvg.vue"
import Menu from "./components/Menu.vue"
import ThemeSwitch from "./components/ThemeSwitch.vue"
import { WindowControls, WindowTitlebar } from "./tauri-controls"

type platform = "windows" | "macos" | "gnome"
const platforms: platform[] = ["windows", "macos", "gnome"]
</script>

<template>
  <div
    class="h-screen overflow-auto bg-slate-200 text-black/90 dark:bg-slate-900 dark:text-white"
  >
    <div class="flex w-[960px] flex-col space-y-3 px-14 py-6">
      <ThemeSwitch />
      <span class="w-fit rounded-sm bg-violet-200/20 px-2 font-mono">
        @tauri-controls-v2/vue
      </span>
      <span
        class="w-fit border-b border-slate-400 pr-10 pb-1 text-lg font-semibold dark:border-slate-600"
      >
        WindowControls
      </span>
      <!-- {/* OnlyControls */} -->
      <div
        class="flex w-fit space-x-3 rounded-xl border border-dashed border-slate-400 p-3 shadow-sm dark:border-slate-600"
      >
        <WindowControls
          v-for="platform in platforms"
          :key="platform"
          :platform="platform"
        />
      </div>
      justify=true:
      <div class="flex border" data-tauri-drag-region>
        <WindowControls platform="windows" justify />
      </div>
      <div class="flex border" data-tauri-drag-region>
        <WindowControls platform="macos" justify />
      </div>
      <span
        class="w-fit border-b border-slate-400 pr-10 pb-1 text-lg font-semibold dark:border-slate-600"
      >
        WindowTitlebar
      </span>
      <WindowTitlebar class="border">content</WindowTitlebar>
      <!-- {/* Icon+Title Controls */} -->
      <WindowTitlebar
        controlsOrder="platform"
        v-for="platform in platforms"
        :key="platform"
        :windowControlsProps="{ platform }"
        class="h-10 rounded-t-lg border border-dashed border-slate-400 bg-white shadow dark:border-slate-600 dark:bg-slate-800"
      >
        <div
          class="flex h-full w-full items-center justify-center"
          data-tauri-drag-region
        >
          <LogoSvg />
          Title
        </div>
      </WindowTitlebar>
      <!-- {/* Icon Menu Title Controls */} -->
      <WindowTitlebar
        v-for="platform in platforms"
        :key="platform"
        :windowControlsProps="{ platform }"
        controlsOrder="platform"
        class="h-10 rounded-t-lg bg-white shadow dark:bg-slate-800"
        data-tauri-drag-region
      >
        <div class="ml-3 flex items-center" data-tauri-drag-region>
          <LogoSvg />
          <Menu />
        </div>
        <div
          class="flex w-full items-center justify-center"
          data-tauri-drag-region
        >
          Title
        </div>
      </WindowTitlebar>
      <WindowTitlebar
        data-tauri-drag-region
        controlsOrder="right"
        :windowControlsProps="{
          platform: 'macos',
          className: 'bg-rose-700 rounded-full p-2',
        }"
      >
        <div
          class="flex items-center justify-center rounded-full bg-sky-500 px-2"
        >
          titlebar content without w-full (macos but on the right side)
        </div>
      </WindowTitlebar>
      <WindowTitlebar
        data-tauri-drag-region
        controlsOrder="left"
        :windowControlsProps="{
          platform: 'windows',
          className: 'bg-rose-700 rounded-full overflow-hidden',
        }"
      >
        <div
          class="flex items-center justify-center rounded-full bg-sky-500 px-2"
        >
          titlebar content without w-full (windows but on the left side)
        </div>
      </WindowTitlebar>
    </div>
  </div>
</template>

// apps/tauri-controls/src/App.tsx
import "./style.css"
import React, { useState } from "react"
import { WindowControls } from "./tauri-controls/window-controls"
import { WindowTitlebar } from "./tauri-controls/window-titlebar"

function App() {
  return (
    <div className="h-screen overflow-auto bg-slate-200 text-black/90 dark:bg-slate-900 dark:text-white">
      <div className="flex w-[960px] flex-col space-y-3 px-14 py-6">
        <ThemeSwitch />
        <span className="w-fit rounded-sm bg-violet-200/20 px-2 font-mono">
          tauri-controls
        </span>
        <span className="w-fit border-b border-slate-400 pr-10 pb-1 text-lg font-semibold dark:border-slate-600">
          WindowControls
        </span>
        {/* OnlyControls */}
        <div className="flex w-fit space-x-3 rounded-xl border border-dashed border-slate-400 p-3 shadow-sm dark:border-slate-600">
          {platforms.map((x) => (
            <OnlyControls key={x} platform={x} />
          ))}
        </div>
        justify=true:
        <div className="flex border" data-tauri-drag-region>
          <WindowControls platform="windows" justify={true} />
        </div>
        <div className="flex border" data-tauri-drag-region>
          <WindowControls platform="macos" justify={true} />
        </div>
        <span className="w-fit border-b border-slate-400 pr-10 pb-1 text-lg font-semibold dark:border-slate-600">
          WindowTitlebar
        </span>
        <WindowTitlebar className="border">content</WindowTitlebar>
        {/* Icon+Title Controls */}
        {platforms.map((x) => (
          <IMC key={x} platform={x} />
        ))}
        {/* Icon Menu Title Controls */}
        {platforms.map((x) => (
          <IMTC key={x} platform={x} />
        ))}
        <WindowTitlebar
          controlsOrder="right"
          windowControlsProps={{
            platform: "macos",
            className: "bg-rose-700 rounded-full p-2",
          }}
        >
          <div className="flex items-center justify-center rounded-full bg-sky-500 px-2">
            titlebar content without w-full (macos but on the right side)
          </div>
        </WindowTitlebar>
        <WindowTitlebar
          controlsOrder="left"
          windowControlsProps={{
            platform: "windows",
            className: "bg-rose-700 rounded-full overflow-hidden",
          }}
        >
          <div className="flex items-center justify-center rounded-full bg-sky-500 px-2">
            titlebar content without w-full (windows but on the left side)
          </div>
        </WindowTitlebar>
      </div>
    </div>
  )
}

const Content = () => {
  const Inside = () => (
    <span className="border border-black/[.07]">Content</span>
  )
  return (
    <>
      <div className="flex w-full items-center justify-center bg-yellow-300">
        <Inside />
      </div>
      <div className="flex w-full items-center justify-center bg-rose-300">
        <Inside />
      </div>
      <div className="flex w-[1300px] items-center justify-center bg-sky-300">
        <Inside />
      </div>
    </>
  )
}

const platforms = ["windows", "macos", "gnome"]

const OnlyControls = ({ platform }: any) => {
  return <WindowControls platform={platform} />
}

/* Icon+Title Controls */
const IMC = ({ platform }: any) => {
  return (
    <WindowTitlebar
      controlsOrder="platform"
      className="h-10 rounded-t-lg border border-dashed border-slate-400 bg-white shadow dark:border-slate-600 dark:bg-slate-800"
      windowControlsProps={{ platform: platform, className: "" }}
    >
      <div
        className="flex h-full w-full items-center justify-center"
        data-tauri-drag-region
      >
        <LogoSvg />
        Title
      </div>
    </WindowTitlebar>
  )
}

/* Icon Menu Title Controls */
const IMTC = ({ platform }: any) => {
  return (
    <WindowTitlebar
      controlsOrder="platform"
      className="h-10 rounded-t-lg bg-white shadow dark:bg-slate-800"
      windowControlsProps={{
        platform: platform,
      }}
      data-tauri-drag-region
    >
      <div className="ml-3 flex items-center" data-tauri-drag-region>
        <LogoSvg />
        <Menu />
      </div>

      <div
        className="flex w-full items-center justify-center"
        data-tauri-drag-region
      >
        Title
      </div>
    </WindowTitlebar>
  )
}

const Menu = () => {
  const items = ["File", "Edit", "View", "Account", "Theme"]

  return (
    <div className="flex flex-row space-x-2 rounded-md px-2 py-1 whitespace-nowrap shadow">
      {items.map((x) => (
        <span key={x}>{x}</span>
      ))}
    </div>
  )
}

const ThemeSwitch = () => {
  function toggle() {
    document.documentElement.classList.toggle("dark")
  }

  return (
    <button
      className="fixed top-1 right-1 rounded-xl bg-slate-300 p-2 font-mono font-semibold shadow-sm dark:bg-slate-950/50"
      onClick={toggle}
    >
      Toggle Theme
    </button>
  )
}

const LogoSvg = () => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="20"
    height="20"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
    className="lucide lucide-sailboat mr-2 text-sky-600/70 dark:text-sky-300/70"
  >
    <path d="M22 18H2a4 4 0 0 0 4 4h12a4 4 0 0 0 4-4Z" />
    <path d="M21 14 10 2 3 14h18Z" />
    <path d="M10 2v16" />
  </svg>
)

export default App
