// apps/tauri-controls/src/tauri-controls/window-titlebar.tsx
import type { OsType } from "@tauri-apps/plugin-os"
import { useEffect, useState } from "react"
import { cn } from "src/tauri-controls/libs/utils"
import { getOsType } from "./libs/plugin-os"
import type { WindowTitlebarProps } from "./types"
import { WindowControls } from "./window-controls"

export function WindowTitlebar({
  children,
  controlsOrder = "system",
  className,
  windowControlsProps,
  ...props
}: WindowTitlebarProps) {
  const [osType, setOsType] = useState<OsType | undefined>(undefined)

  useEffect(() => {
    getOsType().then((type) => {
      setOsType(type)
    })
  }, [])

  const left =
    controlsOrder === "left" ||
    (controlsOrder === "platform" &&
      windowControlsProps?.platform === "macos") ||
    (controlsOrder === "system" && osType === "macos")

  const customProps = (ml: string) => {
    if (windowControlsProps?.justify !== undefined) return windowControlsProps

    const {
      justify: windowControlsJustify,
      className: windowControlsClassName,
      ...restProps
    } = windowControlsProps || {}
    return {
      justify: false,
      className: cn(windowControlsClassName, ml),
      ...restProps,
    }
  }

  return (
    <div className="tauri-controls" style={{ display: "contents" }}>
      <div
        className={cn(
          "bg-background flex flex-row overflow-hidden select-none",
          className
        )}
        data-tauri-drag-region
        {...props}
      >
        {left ? (
          <>
            <WindowControls {...customProps("ml-0")} />
            {children}
          </>
        ) : (
          <>
            {children}
            <WindowControls {...customProps("ml-auto")} />
          </>
        )}
      </div>
    </div>
  )
}

// apps/tauri-controls-svelte/src/lib/WindowTitlebar.svelte
<script lang="ts">
  import { osType } from "$lib/utils/os"
  import { cn } from "$lib/utils/utils"
  import type { WindowControlsProps } from "./types"
  import WindowControls from "./WindowControls.svelte"

  export let controlsOrder = "system"
  export let windowControlsProps: WindowControlsProps = {}

  const left =
    controlsOrder === "left" ||
    (controlsOrder === "platform" &&
      windowControlsProps?.platform === "macos") ||
    (controlsOrder === "system" && osType === "macos")

  const props = (ml: string) => {
    if (windowControlsProps?.justify !== undefined) return windowControlsProps

    const {
      justify: windowControlsJustify,
      class: windowControlsClass,
      ...restProps
    } = windowControlsProps
    return {
      justify: false,
      class: cn(windowControlsClass, ml),
      ...restProps
    }
  }
</script>

<div class="tauri-controls" style="display: contents">
  <div
    {...$$props}
    class={cn(
      "bg-background flex select-none flex-row overflow-hidden",
      $$props.class
    )}
    data-tauri-drag-region
  >
    {#if left}
      <WindowControls {...props("ml-0")} />
      <slot />
    {:else}
      <slot />
      <WindowControls {...props("ml-auto")} />
    {/if}
  </div>
</div>
