// apps/tauri-controls/src/tauri-controls/window-titlebar.tsx
import type { OsType } from "@tauri-apps/plugin-os"
import { useEffect, useState } from "react"
import { cn } from "src/tauri-controls/libs/utils"
import { getOsType } from "./libs/plugin-os"
import type { WindowTitlebarProps } from "./types"
import { WindowControls } from "./window-controls"

export function WindowTitlebar({
  children,
  controlsOrder = "system",
  className,
  windowControlsProps,
  ...props
}: WindowTitlebarProps) {
  const [osType, setOsType] = useState<OsType | undefined>(undefined)

  useEffect(() => {
    getOsType().then((type) => {
      setOsType(type)
    })
  }, [])

  const left =
    controlsOrder === "left" ||
    (controlsOrder === "platform" &&
      windowControlsProps?.platform === "macos") ||
    (controlsOrder === "system" && osType === "macos")

  const customProps = (ml: string) => {
    if (windowControlsProps?.justify !== undefined) return windowControlsProps

    const {
      justify: windowControlsJustify,
      className: windowControlsClassName,
      ...restProps
    } = windowControlsProps || {}
    return {
      justify: false,
      className: cn(windowControlsClassName, ml),
      ...restProps,
    }
  }

  return (
    <div className="tauri-controls" style={{ display: "contents" }}>
      <div
        className={cn(
          "bg-background flex flex-row overflow-hidden select-none",
          className
        )}
        data-tauri-drag-region
        {...props}
      >
        {left ? (
          <>
            <WindowControls {...customProps("ml-0")} />
            {children}
          </>
        ) : (
          <>
            {children}
            <WindowControls {...customProps("ml-auto")} />
          </>
        )}
      </div>
    </div>
  )
}

// apps/tauri-controls-solid/src/tauri-controls/window-titlebar.tsx
import { createMemo, createResource, mergeProps, splitProps } from "solid-js"
import { twMerge } from "tailwind-merge"
import { getOsType } from "./libs/plugin-os"
import type { WindowTitlebarProps } from "./types"
import { WindowControls } from "./window-controls"

export function WindowTitlebar(props: WindowTitlebarProps) {
  const [local, otherProps] = splitProps(props, [
    "children",
    "controlsOrder",
    "class",
    "windowControlsProps",
  ])

  const [osType] = createResource(getOsType)

  const left = createMemo(() => {
    if (local.controlsOrder === "left") return true
    if (local.controlsOrder === "right") return false
    if (local.controlsOrder === "platform") {
      return (local.windowControlsProps?.platform ?? osType()) === "macos"
    }
    // `local.controlsOrder` defaults to "system"
    return osType() === "macos"
  })

  const windowControlsProps = mergeProps(local.windowControlsProps, {
    justify: false,
    get class() {
      const ml = left() ? "ml-0" : "ml-auto"
      return twMerge(local.windowControlsProps?.class, ml)
    },
  })

  const controls = <WindowControls {...windowControlsProps} />

  return (
    <div class="tauri-controls" style={{ display: "contents" }}>
      <div
        class={twMerge(
          "bg-background flex flex-row overflow-hidden select-none",
          local.class
        )}
        data-tauri-drag-region
        {...otherProps}
      >
        {left() ? [controls, local.children] : [local.children, controls]}
      </div>
    </div>
  )
}
